name: Update Pacman Game
on:
  schedule:
    - cron: "0 0 * * *" # Runs daily
  workflow_dispatch:
jobs:
  generate-pacman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: liununu/github-contribution-grid-snake-pacman@main
        with:
          github_user_name: PiYuShKuMaR999
          output: assets/pacman.svg
      - run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add assets/pacman.svg
          git commit -m "Update Pacman"
          git push
