name: Pacman Contribution Game
on:
  schedule:
    - cron: "30 0 * * *"  # Runs daily at 12:30 AM UTC
  workflow_dispatch:       # Allows manual runs

jobs:
  generate-pacman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Generate Pacman
        uses: liununu/github-contribution-grid-snake-pacman@main
        with:
          github_user_name: PiYuShKuMaR999
          output: assets/game.svg
          theme: dark  # Options: dark/light/halloween/etc.
          
      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/game.svg
          git commit -m "Update Pacman game"
          git push
